//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppDemo.AdoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.Recipe = new HashSet<Recipe>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int MaterialTypeId { get; set; }
        public string PackageAmount { get; set; }
        public int MeasurementTypeId { get; set; }
        public int TotalCount { get; set; }
        public int MinBalance { get; set; }
        public decimal Cost { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        public virtual MeasurementType MeasurementType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipe> Recipe { get; set; }
    }
}
