//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppDemo.AdoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Recipe = new HashSet<Recipe>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Articul { get; set; }
        public decimal MinCost { get; set; }
        public byte[] Image { get; set; }
        public int ProductTypeId { get; set; }
        public int WorkersCount { get; set; }
        public int WorkshopId { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        public virtual Workshop Workshop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipe> Recipe { get; set; }
    }
}
